// Bundles the WebView page script (with zod/mini) into a TypeScript string module.
import { mkdirSync, writeFileSync } from "node:fs";
import { build } from "esbuild";

const result = await build({
  entryPoints: [new URL("../src/page.ts", import.meta.url).pathname],
  bundle: true,
  format: "iife",
  platform: "browser",
  // System WebViews on the supported iOS (16+) and Android versions run ES2022.
  target: ["es2022", "safari16", "chrome110"],
  minify: true,
  write: false,
  legalComments: "none",
});
const code = result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const out = new URL("../generated/", import.meta.url);
mkdirSync(out, { recursive: true });
writeFileSync(
  new URL("page-script.ts", out),
  `// Generated by scripts/build.mjs from src/page.ts. Do not edit.\nexport const PAGE_SCRIPT = ${JSON.stringify(code)};\n`,
);
console.log(`player page script: ${(code.length / 1024).toFixed(1)} KB`);
